import { defineConfig } from 'eslint/config'
import globals from 'globals'

export default defineConfig([
	{
		languageOptions: {
			ecmaVersion: 'latest',
			sourceType: 'module',
			globals: {
				sap: 'readonly',
				...globals.browser
			},
		},
		rules: {
			'no-console': 'warn',
			'linebreak-style': 0,
			'brace-style': ['error', '1tbs', { allowSingleLine: true, }],
			'consistent-this': 2,
			'no-div-regex': 2,
			'no-floating-decimal': 2,
			'no-self-compare': 2,
			'no-mixed-spaces-and-tabs': [2, true],
			'no-multiple-empty-lines': ['error', { max: 1, }],
			'no-unused-vars': 'error',
			'no-undef': 'error',
			'no-nested-ternary': 2,
			radix: 2,
			'keyword-spacing': 2,
			'space-unary-ops': 2,
			'wrap-iife': [2, 'any'],
			'array-element-newline': [
				'error',
				{
					ArrayExpression: 'consistent',
					ArrayPattern: { minItems: 3, },
				},
			],
			camelcase: 1,
			'consistent-return': 1,
			'max-nested-callbacks': [1, 3],
			'new-cap': 1,
			'no-extra-boolean-cast': 1,
			'no-lonely-if': 1,
			'no-new': 1,
			'no-new-wrappers': 1,
			'no-redeclare': 1,
			'no-unused-expressions': 1,
			'no-use-before-define': [1, 'nofunc'],
			'no-warning-comments': 1,
			strict: 1,
			'default-case': 1,
			'dot-notation': 0,
			'eol-last': 0,
			eqeqeq: 0,
			'no-trailing-spaces': 'warn',
			'no-irregular-whitespace': 'warn',
			'no-underscore-dangle': 0,
			'key-spacing': ['error', { beforeColon: false, afterColon: true }],
			'no-multi-spaces': 2,
			'no-shadow': 0,
			'no-var': 2,
			'no-const-assign': 2,
			'prefer-const': 2,
			'object-curly-spacing': ['error', 'always'],
			'comma-spacing': ['error', { before: false, after: true }],
			'space-before-function-paren': ['error', 'always'],
			'block-spacing': ['error', 'never'],
			quotes: ['error', 'single'],
			indent: ['error', 'tab'],
			semi: ['error', 'never'],
		},
	},
])
